export const beerStyles = {
  IPA: [
    "IPA",
    "American IPA",
    "West Coast IPA",
    "New England IPA",
    "Double IPA",
    "Triple IPA",
    "Black IPA",
    "English IPA",
    "Hazy IPA",
    "Imperial IPA",
    "Red IPA",
    "Sour IPA",
  ],
  Lager: [
    "Lager",
    "American Lager",
    "Munich Lager",
    "Dortmunder Export",
    "Kellerbier",
    "Märzen",
    "Schwarzbier",
    "Mexican Lager",
    "Dark Lager",
    "Light Lager",
  ],
  Pilsner: [
    "Pilsner",
    "German Pilsner",
    "Czech Pilsner",
    "American Pilsner",
    "Imperial Pilsner",
    "Italian Pilsner",
    "Bohemian Pilsner",
    "Classic Pilsner",
  ],
  Pale_Ale: [
    "Pale Ale",
    "American Pale Ale",
    "English Pale Ale",
    "Australian Pale Ale",
    "Belgian Pale Ale",
    "Extra Pale Ale",
  ],
  Blonde_and_Golden: ["Blonde Ale", "Golden Ale"],
  Stout: [
    "Stout",
    "Nitro Stout",
    "Irish Dry Stout",
    "Milk Stout",
    "Oatmeal Stout",
    "Imperial Stout",
    "Pastry Stout",
    "Chocolate Stout",
    "Oyster Stout",
    "Russian Imperial Stout",
  ],
  Porter: [
    "Porter",
    "English Porter",
    "American Porter",
    "Baltic Porter",
    "Robust Porter",
    "Vanilla Porter",
    "Imperial Porter",
  ],
  Wheat_Beer: [
    "Hefeweizen",
    "American Wheat",
    "Witbier",
    "Dunkelweizen",
    "Kristallweizen",
    "Wheat Ale",
    "Fruited Wheat",
  ],
  Sour: [
    "Sour",
    "Wild Ale",
    "Gose",
    "Berliner Weisse",
    "American Wild Ale",
    "Lambic",
    "Oud Bruin",
    "Kettle Sour",
    "Pastry Sour",
    "Fruited Sour",
  ],
  Belgian: [
    "Belgian Tripel",
    "Belgian Dubbel",
    "Belgian Quadrupel",
    "Belgian Blonde",
    "Belgian Strong Ale",
    "Abbey Ale",
    "Trappist Ale",
  ],
  Amber_and_Red: [
    "American Amber Ale",
    "Irish Red Ale",
    "Flanders Red Ale",
    "Altbier",
    "Red Lager",
    "Vienna Lager",
  ],
  Brown_Ale: [
    "English Brown Ale",
    "American Brown Ale",
    "Nut Brown Ale",
    "Northern English Brown",
    "Southern English Brown",
  ],
  Strong_Ale: [
    "Barleywine",
    "Scotch Ale",
    "Wee Heavy",
    "Old Ale",
    "English Strong Ale",
    "American Strong Ale",
    "Wheatwine",
  ],
  Farmhouse: [
    "Saison",
    "Bière de Garde",
    "Farmhouse Ale",
    "Grisette",
    "Mixed Fermentation Saison",
  ],
  Bock: [
    "Traditional Bock",
    "Doppelbock",
    "Maibock",
    "Eisbock",
    "Weizenbock",
    "Helles Bock",
  ],
  Fruit_Beer: [
    "Fruit IPA",
    "Fruit Sour",
    "Cherry Beer",
    "Raspberry Beer",
    "Apricot Beer",
    "Grapefruit Beer",
    "Berry Beer",
  ],
  Bitter: [
    "Extra Special Bitter",
    "Special Bitter",
    "Ordinary Bitter",
    "English Bitter",
    "Best Bitter",
  ],
  Cider: ["Dry Cider", "Sweet Cider", "Perry", "New England Cider"],
  Mead: ["Traditional Mead", "Fruit Mead", "Melomel", "Spiced Mead", "Braggot"],
  Specialty: [
    "Smoked Beer",
    "Coffee Beer",
    "Herb/Spice Beer",
    "Wood-Aged Beer",
    "Gluten-Free Beer",
    "Rye Beer",
    "Black Ale",
    "Rauchbier",
    "Pumpkin Beer",
  ],
  Low_No_Alcohol: [
    "Non-Alcoholic IPA",
    "Non-Alcoholic Stout",
    "Low Alcohol Beer",
    "Alcohol-Free Lager",
    "Session Beer",
    "Table Beer",
    "Radler",
    "Shandy",
  ],
};
